import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';

@Component({
  selector: 'app-movie-list',
  imports: [CommonModule],
  templateUrl: './movie-list.html',
  styleUrl: './movie-list.css'
})
export class MovieList {
   searchValue = '';
   userRate = 0;

      myMovie = [
    {
      adult: false,
      backdrop_path: '/iZLqwEwUViJdSkGVjePGhxYzbDb.jpg',
      genre_ids: [878, 53],
      id: 755898,
      original_language: 'en',
      original_title: 'War of the Worlds',
      overview:
        'Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.',
      popularity: 2470.4836,
      poster_path: '/yvirUYrva23IudARHn3mMGVxWqM.jpg',
      release_date: '2025-07-29',
      title: 'War of the Worlds',
      video: false,
      vote_average: 4.5,
      vote_count: 180,
    },
    {
      adult: false,
      backdrop_path: '/fQOV47FHTJdaSuSUNlzP3zXUZWE.jpg',
      genre_ids: [878, 12, 28],
      id: 1234821,
      original_language: 'en',
      original_title: 'Jurassic World Rebirth',
      overview:
        "Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world's three most massive dinosaurs. When Zora's operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that's been hidden from the world for decades.",
      popularity: 1029.285,
      poster_path: '/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg',
      release_date: '2025-07-01',
      title: 'Jurassic World Rebirth',
      video: false,
      vote_average: 6.438,
      vote_count: 1055,
    },
    {
      adult: false,
      backdrop_path: '/iZztGzckOMByRRQgsFh2yk3udkU.jpg',
      genre_ids: [28, 27, 10749],
      id: 986206,
      original_language: 'en',
      original_title: 'Night Carnage',
      overview:
        'A blogger who is also a werewolf meets a dashing playboy with a dark secret of his own. Starring Logan Andrews and Christian Howard.',
      popularity: 637.2363,
      poster_path: '/w0wjPQKhlqisSbylf1sWZiNyc2h.jpg',
      release_date: '2025-07-29',
      title: 'Night Carnage',
      video: false,
      vote_average: 5.1,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: '/6WqqEjiycNvDLjbEClM1zCwIbDD.jpg',
      genre_ids: [27, 53, 878],
      id: 1100988,
      original_language: 'en',
      original_title: '28 Years Later',
      overview:
        'Twenty-eight years since the rage virus escaped a biological weapons laboratory, now, still in a ruthlessly enforced quarantine, some have found ways to exist amidst the infected. One such group lives on a small island connected to the mainland by a single, heavily-defended causeway. When one member departs on a mission into the dark heart of the mainland, he discovers secrets, wonders, and horrors that have mutated not only the infected but other survivors as well.',
      popularity: 377.5054,
      poster_path: '/mIg1qCkVxnAlM2TK3RUF0tdEXlE.jpg',
      release_date: '2025-06-18',
      title: '28 Years Later',
      video: false,
      vote_average: 6.91,
      vote_count: 943,
    },
    {
      adult: false,
      backdrop_path: '/1RgPyOhN4DRs225BGTlHJqCudII.jpg',
      genre_ids: [16, 28, 14, 53],
      id: 1311031,
      original_language: 'ja',
      original_title: '劇場版「鬼滅の刃」無限城編 第一章 猗窩座再来',
      overview:
        "As the Demon Slayer Corps members and Hashira engaged in a group strength training program, the Hashira Training, in preparation for the forthcoming battle against the demons, Muzan Kibutsuji appears at the Ubuyashiki Mansion. With the head of the Demon Corps in danger, Tanjiro and the Hashira rush to the headquarters but are plunged into a deep descent to a mysterious space by the hands of Muzan Kibutsuji.  The destination of where Tanjiro and Demon Slayer Corps have fallen is the demons' stronghold – the Infinity Castle. And so, the battleground is set as the final battle between the Demon Slayer Corps and the demons ignites.",
      popularity: 393.2631,
      poster_path: '/wjtxgr7yHM8aTVOhlUSycfVTspI.jpg',
      release_date: '2025-07-18',
      title: 'Demon Slayer: Kimetsu no Yaiba Infinity Castle',
      video: false,
      vote_average: 7.038,
      vote_count: 66,
    },
    {
      adult: false,
      backdrop_path: '/cEQMqB3ahd4mfeUN6VGC0ouVnZZ.jpg',
      genre_ids: [28, 878, 53],
      id: 1071585,
      original_language: 'en',
      original_title: 'M3GAN 2.0',
      overview:
        "After the underlying tech for M3GAN is stolen and misused by a powerful defense contractor to create a military-grade weapon known as Amelia, M3GAN's creator Gemma realizes that the only option is to resurrect M3GAN and give her a few upgrades, making her faster, stronger, and more lethal.",
      popularity: 282.5437,
      poster_path: '/4a63rQqIDTrYNdcnTXdPsQyxVLo.jpg',
      release_date: '2025-06-25',
      title: 'M3GAN 2.0',
      video: false,
      vote_average: 7.606,
      vote_count: 620,
    },
    {
      adult: false,
      backdrop_path: '/xvP4WFn7TZvkCeZA4IhD6H9XjRa.jpg',
      genre_ids: [28, 35, 80],
      id: 1106289,
      original_language: 'en',
      original_title: 'The Pickup',
      overview:
        'A routine cash pickup takes a wild turn when mismatched armored truck drivers Russell and Travis are ambushed by ruthless criminals led by savvy mastermind Zoe.',
      popularity: 264.0599,
      poster_path: '/vFWvWhfAvij8UIngg2Vf6JV95Cr.jpg',
      release_date: '2025-07-27',
      title: 'The Pickup',
      video: false,
      vote_average: 6.063,
      vote_count: 40,
    },
    {
      adult: false,
      backdrop_path: '/1KwliRKTw61fRGmbG4Sf8eWOHP.jpg',
      genre_ids: [28, 35, 80],
      id: 1181540,
      original_language: 'en',
      original_title: 'Guns Up',
      overview:
        'When a job goes horribly wrong, an ex-cop and family man who moonlights as a mob henchman has one night to get his family out of the city.',
      popularity: 232.5786,
      poster_path: '/3RokBWEkQqJRZEVP3DPwGm5MYh6.jpg',
      release_date: '2025-05-15',
      title: 'Guns Up',
      video: false,
      vote_average: 6.884,
      vote_count: 56,
    },
    {
      adult: false,
      backdrop_path: '/x5dVPttNDZaVRTvbk7pYrtGZoZN.jpg',
      genre_ids: [35, 18],
      id: 1263256,
      original_language: 'en',
      original_title: 'Happy Gilmore 2',
      overview:
        "Happy Gilmore isn't done with golf — not by a long shot. Since his retirement after his first Tour Championship win, Gilmore returns to finance his daughter's ballet classes.",
      popularity: 221.5603,
      poster_path: '/ynT06XivgBDkg7AtbDbX1dJeBGY.jpg',
      release_date: '2025-07-25',
      title: 'Happy Gilmore 2',
      video: false,
      vote_average: 6.677,
      vote_count: 468,
    },
    {
      adult: false,
      backdrop_path: '/s94NjfKkcSczZ1FembwmQZwsuwY.jpg',
      genre_ids: [878, 12],
      id: 617126,
      original_language: 'en',
      original_title: 'The Fantastic 4: First Steps',
      overview:
        "Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel's First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.",
      popularity: 230.4035,
      poster_path: '/x26MtUlwtWD26d0G0FXcppxCJio.jpg',
      release_date: '2025-07-23',
      title: 'The Fantastic 4: First Steps',
      video: false,
      vote_average: 7.3,
      vote_count: 826,
    },
    {
      adult: false,
      backdrop_path: '/eU7IfdWq8KQy0oNd4kKXS0QUR08.jpg',
      genre_ids: [878, 12, 28],
      id: 1061474,
      original_language: 'en',
      original_title: 'Superman',
      overview:
        'Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.',
      popularity: 230.1534,
      poster_path: '/ombsmhYUqR4qqOLOxAyr5V8hbyv.jpg',
      release_date: '2025-07-09',
      title: 'Superman',
      video: false,
      vote_average: 7.686,
      vote_count: 1558,
    },
    {
      adult: false,
      backdrop_path: '/A466i5iATrpbVjX30clP1Zyfp31.jpg',
      genre_ids: [10749, 35, 18],
      id: 1307078,
      original_language: 'en',
      original_title: 'My Oxford Year',
      overview:
        'An ambitious American fulfilling her dream of studying at Oxford falls for a charming Brit hiding a secret that may upend her perfectly planned life.',
      popularity: 241.1602,
      poster_path: '/jrhXbIOFingzdLjkccjg9vZnqIp.jpg',
      release_date: '2025-07-31',
      title: 'My Oxford Year',
      video: false,
      vote_average: 7.335,
      vote_count: 118,
    },
    {
      adult: false,
      backdrop_path: '/7Q2CmqIVJuDAESPPp76rWIiA0AD.jpg',
      genre_ids: [28, 12, 18],
      id: 1011477,
      original_language: 'en',
      original_title: 'Karate Kid: Legends',
      overview:
        "After a family tragedy, kung fu prodigy Li Fong is uprooted from his home in Beijing and forced to move to New York City with his mother. When a new friend needs his help, Li enters a karate competition – but his skills alone aren't enough. Li's kung fu teacher Mr. Han enlists original Karate Kid Daniel LaRusso for help, and Li learns a new way to fight, merging their two styles into one for the ultimate martial arts showdown.",
      popularity: 210.1505,
      poster_path: '/AEgggzRr1vZCLY86MAp93li43z.jpg',
      release_date: '2025-05-08',
      title: 'Karate Kid: Legends',
      video: false,
      vote_average: 7.133,
      vote_count: 598,
    },
    {
      adult: false,
      backdrop_path: '/2DcD4Hh80SW7YVpwckkiEFRZX06.jpg',
      genre_ids: [28, 35],
      id: 1124619,
      original_language: 'en',
      original_title: 'Bride Hard',
      overview:
        'Sam is a secret agent whose toughest mission to date is pleasing her bride-to-be best friend at a lavish destination wedding. When a team of mercenaries crashes the party and takes the guests hostage, Sam is thrown into a fight unlike any before — one where she can’t risk blowing her cover or ruining the big day. As she takes on the bad guys in a high-stakes battle disguised as a fairy-tale affair, she realizes the real threat might be closer than she thinks.',
      popularity: 173.7357,
      poster_path: '/3mExdWLSxAiUCb4NMcYmxSkO7n4.jpg',
      release_date: '2025-06-19',
      title: 'Bride Hard',
      video: false,
      vote_average: 5.805,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: '/oPgXVSdGR9dGwbmvIToOCMmsdc2.jpg',
      genre_ids: [28, 53, 80],
      id: 541671,
      original_language: 'en',
      original_title: 'Ballerina',
      overview:
        'Taking place during the events of John Wick: Chapter 3 – Parabellum, Eve Macarro begins her training in the assassin traditions of the Ruska Roma.',
      popularity: 169.2009,
      poster_path: '/2VUmvqsHb6cEtdfscEA6fqqVzLg.jpg',
      release_date: '2025-06-04',
      title: 'Ballerina',
      video: false,
      vote_average: 7.453,
      vote_count: 1253,
    },
    {
      adult: false,
      backdrop_path: '/xVSrVenIhbhT9DJioOkhmOlxJuq.jpg',
      genre_ids: [27],
      id: 1452176,
      original_language: 'en',
      original_title: "Abraham's Boys: A Dracula Story",
      overview:
        'Following the events of Dracula, Abraham van Helsing moves his two sons, Max and Rudy, to the US in an attempt to escape their past. It does not work.',
      popularity: 143.6004,
      poster_path: '/e10AbPwcJk5b7ja3MQUVr5wHEeq.jpg',
      release_date: '2025-07-11',
      title: "Abraham's Boys: A Dracula Story",
      video: false,
      vote_average: 4,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/9l6bcHNFLR2fcCBSPzEeqxiQhwU.jpg',
      genre_ids: [28, 35, 80, 9648],
      id: 1374534,
      original_language: 'nl',
      original_title: "Bad Boa's",
      overview:
        'When an overeager community officer and a reckless ex-detective are forced to team up, plenty of chaos ensues on the streets of Rotterdam.',
      popularity: 123.4389,
      poster_path: '/7bcndiaTgu1Kj5a6qyCmsWYdtI.jpg',
      release_date: '2025-07-10',
      title: 'Almost Cops',
      video: false,
      vote_average: 5.892,
      vote_count: 116,
    },
    {
      adult: false,
      backdrop_path: '/jvpkBenB6hv19WWYVlaiow8zklq.jpg',
      genre_ids: [10751, 35, 80, 12, 16],
      id: 1175942,
      original_language: 'en',
      original_title: 'The Bad Guys 2',
      overview:
        'The now-reformed Bad Guys are trying (very, very hard) to be good, but instead find themselves hijacked into a high-stakes, globe-trotting heist, masterminded by a new team of criminals they never saw coming: The Bad Girls.',
      popularity: 105.6675,
      poster_path: '/26oSPnq0ct59l07QOXZKyzsiRtN.jpg',
      release_date: '2025-07-24',
      title: 'The Bad Guys 2',
      video: false,
      vote_average: 7.6,
      vote_count: 37,
    },
    {
      adult: false,
      backdrop_path: '/qj0GN10AC65FcJchKLTDmOFE15X.jpg',
      genre_ids: [27],
      id: 1189735,
      original_language: 'ga',
      original_title: 'Fréamhacha',
      overview:
        'Care worker Shoo, who is haunted by a personal tragedy, is sent to a remote village to care for an agoraphobic woman, who fears both her neighbours and the Na Sídhe – sinister folkloric entities she believes abducted her decades before.',
      popularity: 97.0804,
      poster_path: '/pfLylbmY0uxQm6Sh63j6bpb7XB3.jpg',
      release_date: '2025-04-25',
      title: 'Fréwaka',
      video: false,
      vote_average: 7,
      vote_count: 13,
    },
    {
      adult: false,
      backdrop_path: '/u2ctOiURF9hL3hmXmEMHxcVPVrQ.jpg',
      genre_ids: [27],
      id: 1242011,
      original_language: 'en',
      original_title: 'Together',
      overview:
        "With a move to the countryside already testing the limits of a couple's relationship, a supernatural encounter begins an extreme transformation of their love, their lives, and their flesh.",
      popularity: 93.0559,
      poster_path: '/inliWt3ukcpKDGPpEe2lRDLwK2r.jpg',
      release_date: '2025-07-28',
      title: 'Together',
      video: false,
      vote_average: 7.6,
      vote_count: 84,
    },
  ];
}